### ISSUE TITLE
runtime error causing lightningd to crash

### ISSUE THREAD

**Issue by ZenenTreadwell** [nbd-wtf/trustedcoin#37]
```
panic: runtime error: index out of range [0] with length 0                                                            
                                                                                                                      
goroutine 199 [running]:                                                                                              
main.main.func5(0xc000152480, 0xc00022f050)                                                                           
        github.com/nbd-wtf/trustedcoin/main.go:167 +0x427                                                             
github.com/fiatjaf/lightningd-gjson-rpc/plugin.handleMessage(0xc000152480, 0xc00006c3c0, {{0xc00015cfc8, 0x3}, {0x75e740, 0xc0004443b0}, {0xc00015cfe0, 0x9}, {0x773e00, 0xc00022f050}})
        github.com/fiatjaf/lightningd-gjson-rpc@v1.6.4-0.20241113234716-c08cd810b4d5/plugin/plugin.go:254 +0x2f0      
created by github.com/fiatjaf/lightningd-gjson-rpc/plugin.(*Plugin).Listener in goroutine 1                           
        github.com/fiatjaf/lightningd-gjson-rpc@v1.6.4-0.20241113234716-c08cd810b4d5/plugin/plugin.go:232 +0xd54      
2025-08-09T21:36:59.270Z INFO    plugin-trustedcoin: Killing plugin: exited during normal operation                   
The Bitcoin backend died.                                                                                             
2025-08-09T21:36:59.270Z **BROKEN** lightningd: The Bitcoin backend died.                                             
lightningd: FATAL SIGNAL 6 (version v25.02.1)                                                                         
0x561533eb94b1 send_backtrace                                                                                         
        common/daemon.c:33                                                                                            
0x561533eb954d crashdump                                                                                              
        common/daemon.c:78                                                                                            
0x7fd3c595c04f ???                                                                                                    
        ???:0                                                                                                         
0x7fd3c59aaebc ???                                                                                                    
        ???:0                                                                                                         
0x7fd3c595bfb1 ???                                                                                                    
        ???:0                                                                                                         
0x7fd3c5946471 ???                                                                                                    
        ???:0                                                                                                         
0x561533e61aee fatal_vfmt                                                                                             
        lightningd/log.c:1043                                                                                         
0x561533e61b8d fatal                                                                                                  
        lightningd/log.c:1053                                                                                         
0x561533e337d7 bitcoin_destructor                                                                                     
        lightningd/bitcoind.c:36                                                                                      
0x561533f8584c notify                                                                                                 
        ccan/ccan/tal/tal.c:246                                                                                       
0x561533f8591f del_tree                                                                                               
        ccan/ccan/tal/tal.c:437                                                                                       
0x561533f85eab tal_free                                                                                               
        ccan/ccan/tal/tal.c:532                                                                                       
0x561533e8702c plugin_kill                                                                                            
        lightningd/plugin.c:457                                                                                       
0x561533e8736a plugin_conn_finish
        lightningd/plugin.c:888                                                                                       
0x561533f7b4d5 destroy_conn                                
        ccan/ccan/io/poll.c:246
0x561533f7b4fb destroy_conn_close_fd
        ccan/ccan/io/poll.c:252
0x561533f8584c notify                                      
        ccan/ccan/tal/tal.c:246
0x561533f8591f del_tree                                    
        ccan/ccan/tal/tal.c:437
0x561533f85eab tal_free                                    
        ccan/ccan/tal/tal.c:532
0x561533f7a012 io_close                                    
        ccan/ccan/io/io.c:496
0x561533f7bb29 io_loop                                     
        ccan/ccan/io/poll.c:459
0x561533e5967b io_loop_with_timers
        lightningd/io_loop_with_timers.c:22
0x561533e5f1a2 main                                        
        lightningd/lightningd.c:1490
0x7fd3c5947249 ???                                         
        ???:0                                              
0x7fd3c5947304 ???                                         
        ???:0                                              
0x561533e3214d ???                                         
        ???:0                                              
0xffffffffffffffff ???                                     
        ???:0                                              
2025-08-09T21:36:59.307Z **BROKEN** lightningd: FATAL SIGNAL 6 (version v25.02.1)
2025-08-09T21:36:59.307Z **BROKEN** lightningd: backtrace: common/daemon.c:41 (send_backtrace) 0x561533eb94fe
2025-08-09T21:36:59.307Z **BROKEN** lightningd: backtrace: common/daemon.c:78 (crashdump) 0x561533eb954d
2025-08-09T21:36:59.307Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fd3c595c04f
2025-08-09T21:36:59.307Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fd3c59aaebc
2025-08-09T21:36:59.307Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fd3c595bfb1
2025-08-09T21:36:59.307Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fd3c5946471
2025-08-09T21:36:59.307Z **BROKEN** lightningd: backtrace: lightningd/log.c:1043 (fatal_vfmt) 0x561533e61aee
2025-08-09T21:36:59.308Z **BROKEN** lightningd: backtrace: lightningd/log.c:1053 (fatal) 0x561533e61b8d
2025-08-09T21:36:59.308Z **BROKEN** lightningd: backtrace: lightningd/bitcoind.c:36 (bitcoin_destructor) 0x561533e337d7
2025-08-09T21:36:59.308Z **BROKEN** lightningd: backtrace: ccan/ccan/tal/tal.c:246 (notify) 0x561533f8584c
2025-08-09T21:36:59.308Z **BROKEN** lightningd: backtrace: ccan/ccan/tal/tal.c:437 (del_tree) 0x561533f8591f
2025-08-09T21:36:59.308Z **BROKEN** lightningd: backtrace: ccan/ccan/tal/tal.c:532 (tal_free) 0x561533f85eab
2025-08-09T21:36:59.308Z **BROKEN** lightningd: backtrace: lightningd/plugin.c:457 (plugin_kill) 0x561533e8702c
2025-08-09T21:36:59.308Z **BROKEN** lightningd: backtrace: lightningd/plugin.c:888 (plugin_conn_finish) 0x561533e8736a
2025-08-09T21:36:59.308Z **BROKEN** lightningd: backtrace: ccan/ccan/io/poll.c:246 (destroy_conn) 0x561533f7b4d5
2025-08-09T21:36:59.308Z **BROKEN** lightningd: backtrace: ccan/ccan/io/poll.c:252 (destroy_conn_close_fd) 0x561533f7b4fb
2025-08-09T21:36:59.309Z **BROKEN** lightningd: backtrace: ccan/ccan/tal/tal.c:246 (notify) 0x561533f8584c
2025-08-09T21:36:59.309Z **BROKEN** lightningd: backtrace: ccan/ccan/tal/tal.c:437 (del_tree) 0x561533f8591f
2025-08-09T21:36:59.309Z **BROKEN** lightningd: backtrace: ccan/ccan/tal/tal.c:532 (tal_free) 0x561533f85eab
2025-08-09T21:36:59.309Z **BROKEN** lightningd: backtrace: ccan/ccan/io/io.c:496 (io_close) 0x561533f7a012
2025-08-09T21:36:59.309Z **BROKEN** lightningd: backtrace: ccan/ccan/io/poll.c:459 (io_loop) 0x561533f7bb29
2025-08-09T21:36:59.309Z **BROKEN** lightningd: backtrace: lightningd/io_loop_with_timers.c:22 (io_loop_with_timers) 0x561533e5967b
2025-08-09T21:36:59.309Z **BROKEN** lightningd: backtrace: lightningd/lightningd.c:1490 (main) 0x561533e5f1a2
2025-08-09T21:36:59.309Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fd3c5947249
2025-08-09T21:36:59.310Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fd3c5947304
2025-08-09T21:36:59.310Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x561533e3214d
2025-08-09T21:36:59.310Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0xffffffffffffffff
```

It's a pretty huge stacktrace and I don't have much of an idea about where to start with it

**Comment by fiatjaf** [comment]
Sorry about that. Fixed in 1128738740904037fec8be98377c02e7dbf19d6c.

**Comment by ZenenTreadwell** [comment]
I'm still encountering this issue, but I should note that I'm running this particular node on my laptop. It's erroring out when my laptop goes to sleep. It's still throwing the error at the given code point:

https://github.com/nbd-wtf/trustedcoin/blob/1128738740904037fec8be98377c02e7dbf19d6c/main.go#L167

**Comment by fiatjaf** [comment]
In that case I don't understand. It should either fail to get a tx or the tx should have the correct output and the error shouldn't happen.

Are you using it with a Bitcoin node running locally too?

**Comment by ZenenTreadwell** [comment]
No, this is happening without a local Bitcoin node. Previously, I was connecting to a node on my LAN and that seemed to be working fairly well, I can try re-enabling that to see what happens but it's hard to reproduce this bug as it usually happens after CLN has been running for a while.

**Comment by fiatjaf** [comment]
I've compiled a new version with more logs (printed to stderr) that may help us find the issue, if you want to try it:

[trustedcoin.txt](https://github.com/user-attachments/files/21792963/trustedcoin.txt) (I've renamed it to ".txt" just so GitHub would allow me to upload it, but it's actually a Linux x86 executable).

Or you can compile it yourself from https://github.com/nbd-wtf/trustedcoin/commit/669f6532dca044936ff42bb3033db534b7dc3b36.

**Comment by ZenenTreadwell** [comment]
got it:

```
##### trying 1067637c903defb440a7b726d59ff766228370ebd8b18ed273c31de4df85b439 on https://blockstream.info/api, got it: { []}##### TX WITH NO VOUT: 1067637c903defb440a7b726d59ff766228370
ebd8b18ed273c31de4df85b439 { []}panic: runtime error: index out of range [1] with length 0  
                                                                                            
goroutine 186 [running]:                                                                    
main.main.func5(0xc0001b78c0, 0xc0002ea240)                                                 
        github.com/nbd-wtf/trustedcoin/main.go:172 +0x4c6                                   
github.com/fiatjaf/lightningd-gjson-rpc/plugin.handleMessage(0xc0001b78c0, 0xc0000682a0, {{0xc00034a120, 0x3}, {0x7885c0, 0xc00009a000}, {0xc00034a123, 0x9}, {0x7abc00, 0xc0002ea240}})
        github.com/fiatjaf/lightningd-gjson-rpc@v1.6.4-0.20241113234716-c08cd810b4d5/plugin/plugin.go:254 +0x2ea
created by github.com/fiatjaf/lightningd-gjson-rpc/plugin.(*Plugin).Listener in goroutine 1 
        github.com/fiatjaf/lightningd-gjson-rpc@v1.6.4-0.20241113234716-c08cd810b4d5/plugin/plugin.go:232 +0xd49
2025-08-15T13:52:35.266Z INFO    plugin-trustedcoin: Killing plugin: exited during normal operation
```

edit: more results
```
2025-08-15T11:20:53.225Z plugin-trustedcoin returning block 557481, 00000000000000000016146847…, 1472824 bytes
##### trying a3d159ec2a93356a72e7e63cb4014c5721b70810df8be390bf61210546e8ee21 on https://mempool.emzy.de/api, got it: {a3d159ec2a93356a72e7e63cb4014c5721b70810df8be390bf61210546e8ee21 [{76a9140f056cdbf64e505f0ff869c4d808847d817a2ca688ac 72000000} {0020701a8d401c84fb13e6baf169d59684e17abd9fa216c8cc5b9fc63d622ff8c58d 15063000}]}##### trying bae042506babda3b380ca4b6dd8e22ad17fbb1efb939e0e6b37b4bda6cd33983 on https://mempool.emzy.de/api, got it: {bae042506babda3b380ca4b6dd8e22ad17fbb1efb939e0e6b37b4bda6cd33983 [{76a9140f056cdbf64e505f0ff869c4d808847d817a2ca688ac 1000000} {0020701a8d401c84fb13e6baf169d59684e17abd9fa216c8cc5b9fc63d622ff8c58d 226837}]}##### trying 961c309d5648a42edc09d8414e71864ac3cfe3213d2dfebba7cdda5d19ccac81 on https://mempool.emzy.de/api, got it: {961c309d5648a42edc09d8414e71864ac3cfe3213d2dfebba7cdda5d19ccac81 [{0020a87691783d245eceaec8d367acfb23ce00eb692cd59907c8661afafbc43ba49a 950332}]}##### trying a0f23451df145929a4d0b02843fc11960d15f52b5b079f5620a283fe7956fbf7 on https://mempool.emzy.de/api, got it: {a0f23451df145929a4d0b02843fc11960d15f52b5b079f5620a283fe7956fbf7 [{a914c7b3c342d951443548e0f191644ff9326517d7b187 256254} {a9141bac339f43c850a746bd63ee2417fe320b1c690087 121783} {76a9143d1c0f069cfa4225270112a67712040ebc38cb9d88ac 100025} {0020a87691783d245eceaec8d367acfb23ce00eb692cd59907c8661afafbc43ba49a 12689878}]}##### trying 5efd5b4ffadc8e818ac3e229d595057da7121b929bd4e516a3ae0aaead2e80b0 on https://blockstream.info/api, got it: { []}##### TX WITH NO VOUT: 5efd5b4ffadc8e818ac3e229d595057da7121b929bd4e516a3ae0aaead2e80b0 { []}panic: runtime error: index out of range [1] with length 0

goroutine 189 [running]:
main.main.func5(0xc0001dd8c0, 0xc000612a80)
        github.com/nbd-wtf/trustedcoin/main.go:172 +0x4c6
github.com/fiatjaf/lightningd-gjson-rpc/plugin.handleMessage(0xc0001dd8c0, 0xc000100240, {{0xc0004d6728, 0x3}, {0x7885c0, 0xc0002ae470}, {0xc0004d6740, 0x9}, {0x7abc00, 0xc000612a80}})
        github.com/fiatjaf/lightningd-gjson-rpc@v1.6.4-0.20241113234716-c08cd810b4d5/plugin/plugin.go:254 +0x2ea
created by github.com/fiatjaf/lightningd-gjson-rpc/plugin.(*Plugin).Listener in goroutine 1
        github.com/fiatjaf/lightningd-gjson-rpc@v1.6.4-0.20241113234716-c08cd810b4d5/plugin/plugin.go:232 +0xd49
2025-08-15T15:20:54.385Z INFO    plugin-trustedcoin: Killing plugin: exited during normal operation
The Bitcoin backend died.
2025-08-15T15:20:54.385Z **BROKEN** lightningd: The Bitcoin backend died.
```

Offending transactions: 
https://blockstream.info/tx/1067637c903defb440a7b726d59ff766228370ebd8b18ed273c31de4df85b439
https://blockstream.info/tx/5efd5b4ffadc8e818ac3e229d595057da7121b929bd4e516a3ae0aaead2e80b0

**Comment by fiatjaf** [comment]
Thank you. I see it now. It was a rookie mistake. I forgot to check if the APIs were returning an empty response, then that response was being interpreted as an empty transaction with no outputs.

**Comment by fiatjaf** [comment]
Should be fixed in d06912c9c865fc08800e739d061f8786bec2b56d and I made a new release. Please let me know if I got it wrong again.

**Comment by ZenenTreadwell** [comment]
I've been running my node on spotty internet all morning, and trustedcoin seems like it's been keeping up - no crashes to CLN. I think the bug is properly fixed, many thanks for sticking with it.
